<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { auth, logout } from '../stores/auth'
import { entities } from '../entities'
const open=ref(false),query=ref(''),busy=ref(false),error=ref(''),router=useRouter()
async function leave(){busy.value=true;error.value='';try{await logout();await router.replace('/login')}catch(e){error.value=e.message}finally{busy.value=false}}
function search(){if(query.value.trim().length>=2)router.push({path:'/search',query:{q:query.value.trim()}})}
</script>
<template><div class="admin-app"><a class="skip" href="#content">Aller au contenu</a><aside :class="{open}" aria-label="Navigation administration"><RouterLink class="brand" to="/dashboard" @click="open=false"><img src="/images/logo-horizontal.webp" alt="BolideMarket"><span>ADMINISTRATION</span></RouterLink><nav @click="open=false"><RouterLink to="/dashboard"><span>01</span>Vue d’ensemble</RouterLink><RouterLink v-for="(entity,key,index) in entities" :key="key" :to="'/'+key"><span>{{ String(index+2).padStart(2,'0') }}</span>{{ entity.title }}</RouterLink><RouterLink to="/reports"><span>11</span>Rapports</RouterLink><RouterLink to="/settings"><span>12</span>Paramètres</RouterLink></nav><div class="admin-profile"><strong>{{ auth.user.name }}</strong><small>Administrateur</small><button :disabled="busy" @click="leave">{{ busy?'Déconnexion…':'Déconnexion →' }}</button><p v-if="error" role="alert">{{ error }}</p></div></aside><button v-if="open" class="scrim" aria-label="Fermer le menu" @click="open=false"/><div class="workspace"><header><button class="menu-toggle secondary" :aria-expanded="open" aria-label="Menu administration" @click="open=!open">☰</button><span class="header-label">Supervision globale</span><form class="global-search" role="search" @submit.prevent="search"><label class="sr-only" for="global-search">Recherche globale</label><input id="global-search" v-model="query" minlength="2" maxlength="120" placeholder="E-mail, boutique ou référence…"><button class="secondary" type="submit">Rechercher</button></form><span class="badge">ADMIN</span></header><main id="content" tabindex="-1"><slot/></main><footer>© 2026 BolideMarket · Administration · Paiements DEMO uniquement</footer></div></div></template>
