<script setup>
import { inject } from 'vue'
import { landingKey } from '../composables/useLandingData'
import { formatDistance } from '../utils/format'
import { marketplaceLink } from '../config'
import AppIcon from './AppIcon.vue'
const { vehicles } = inject(landingKey)
</script>
<template><section class="map-section" aria-labelledby="map-title"><div class="map-art" aria-hidden="true"><svg viewBox="0 0 1200 430" preserveAspectRatio="xMidYMid slice"><defs><pattern id="roads" width="155" height="130" patternUnits="userSpaceOnUse" patternTransform="rotate(-18)"><path d="M0 35h155M28 0v130M110 0v130M0 102h155M60 0l30 130" fill="none" stroke="currentColor" stroke-width="1" /></pattern></defs><rect width="1200" height="430" fill="url(#roads)"/><path d="M50 390C210 250 315 420 465 270S625 210 710 290 865 230 1190 315L1200 440H0Z" fill="#22343e"/><path d="M780 0q-95 50-30 135t-24 164l65 9q140-130 48-187T855 0Z" fill="#22343e"/></svg><span class="map-place cocody">Cocody</span><span class="map-place marcory">Marcory</span><span class="map-place plateau">Plateau</span><span class="map-place bingerville">Bingerville</span><span class="map-place yopougon">Yopougon</span></div><div class="container map-layout"><div data-reveal><h2 id="map-title">Le marché automobile<br /> autour de vous.</h2><p>Les offres les plus proches s’affichent en premier.</p><a class="button button-primary" href="#recherche">Explorer autour de moi <AppIcon /></a><p class="map-disclaimer">Vue illustrative d’Abidjan · pas une carte de navigation.</p></div><div class="map-offers" aria-label="Offres du catalogue"><a v-for="vehicle in vehicles.slice(0, 3)" :key="vehicle.id" :href="marketplaceLink({}, `vehicles/${encodeURIComponent(vehicle.slug)}`)"><span class="map-pin"><AppIcon name="pin" /></span><span>{{ vehicle.title }} <small>{{ vehicle.location.district?.name || vehicle.location.city?.name }}<template v-if="vehicle.distance_km != null"> · {{ formatDistance(vehicle.distance_km) }}</template></small></span></a><p v-if="!vehicles.length" class="map-empty">Choisissez votre ville pour explorer les offres.</p></div></div></section></template>
