<script setup>
import { ref,onMounted,watch,nextTick } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { auth,logout } from '../stores/auth'
import { currentShop,shopState,loadShops,resetShops } from '../stores/shop'
import { config } from '../config'
import { locationLabel } from '../utils/format'
import UserAvatar from './UserAvatar.vue'
import AppIcon from './AppIcon.vue'
import FormError from './FormError.vue'
const route=useRoute(),router=useRouter(),open=ref(false),drawer=ref(null),busy=ref(false),error=ref(null)
const links=[['/dashboard','Vue d’ensemble','home'],['/vehicles','Véhicules','car'],['/reservations','Réservations','calendar'],['/clients','Clients','users'],['/orders','Ventes','chart'],['/price-offers','Propositions de prix','chart'],['/rentals','Locations','key'],['/receipts','Reçus','chart'],['/shop','Boutique','shop'],['/settings','Paramètres','settings']]
onMounted(loadShops)
watch(()=>route.fullPath,()=>{open.value=false})
watch(open,async value=>{await nextTick();if(value)drawer.value.showModal();else drawer.value?.close()})
async function leave(){busy.value=true;error.value=null;try{await logout();resetShops();await router.replace('/login')}catch(e){error.value=e}finally{busy.value=false}}
</script><template><a class="skip-link" href="#main">Aller au contenu</a><div class="pro-shell"><aside class="sidebar"><a class="brand-link" :href="config.landingUrl"><img src="/images/logo-horizontal.webp" alt="BolideMarket"/><b>Pro</b></a><span class="nav-caption">VOTRE ESPACE</span><nav aria-label="Navigation professionnelle"><RouterLink v-for="[path,label,icon] in links" :key="path" :to="path"><AppIcon :name="icon"/>{{ label }}</RouterLink></nav><div class="sidebar-bottom"><a v-if="currentShop" :href="config.marketplaceUrl+'/shops/'+currentShop.slug" target="_blank" rel="noopener">Voir ma boutique publique ↗</a><a :href="config.marketplaceUrl">Voir BolideMarket ↗</a><RouterLink to="/profile">Mon profil</RouterLink><button :disabled="busy" @click="leave">Déconnexion</button></div></aside><div class="workspace"><header class="topbar"><button class="menu-toggle" aria-label="Ouvrir le menu" @click="open=true">☰</button><span>{{ route.meta.title }}</span><div class="topbar-end"><label v-if="shopState.shops.length > 1" class="shop-switch"><span class="sr-only">Boutique active</span><select v-model="shopState.id"><option v-for="s in shopState.shops" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><div class="shop-heading"><strong>{{ currentShop?.name || 'Espace professionnel' }}</strong><small>{{ locationLabel(currentShop?.location) }}</small></div><details class="profile-menu"><summary aria-label="Menu du profil"><UserAvatar :user="auth.user" :src="currentShop?.logo_url"/></summary><div><RouterLink to="/profile">Mon profil</RouterLink><button :disabled="busy" @click="leave">Déconnexion</button></div></details></div></header><main id="main"><FormError :error="error || shopState.error"/><button v-if="shopState.error" class="button secondary" @click="loadShops">Réessayer</button><div v-if="!shopState.ready && !shopState.error" class="loading" role="status">Chargement de votre espace…</div><template v-else-if="shopState.ready"><RouterView :key="route.path + ':' + shopState.id"/></template></main><footer><span>© 2026 BolideMarket Pro</span><span v-if="currentShop?.is_demo">Boutique, véhicules, prix et statistiques de démonstration.</span></footer></div></div><dialog ref="drawer" class="mobile-drawer" aria-label="Navigation professionnelle" @cancel.prevent="open=false"><button class="close-menu" aria-label="Fermer le menu" @click="open=false">×</button><img class="brand" src="/images/logo-horizontal.webp" alt="BolideMarket"/><nav><RouterLink v-for="[path,label] in links" :key="path" :to="path">{{ label }}</RouterLink><RouterLink to="/profile">Mon profil</RouterLink><a v-if="currentShop" :href="config.marketplaceUrl+'/shops/'+currentShop.slug">Voir ma boutique publique ↗</a><a :href="config.marketplaceUrl">Voir BolideMarket ↗</a><button :disabled="busy" @click="leave">Déconnexion</button></nav></dialog></template>