import { beforeEach,describe,it,expect,vi } from 'vitest'
import { mount,flushPromises } from '@vue/test-utils'
import { createRouter,createMemoryHistory } from 'vue-router'
import { get,post,request,csrfCookie } from '../src/services/api'
import { auth,adminGuard,safeDestination,logout,login } from '../src/stores/auth'
import { money,cell } from '../src/entities'
import DashboardPage from '../src/pages/DashboardPage.vue'
import EntityList from '../src/pages/EntityList.vue'
import EntityDetail from '../src/pages/EntityDetail.vue'
import ModerationDialog from '../src/components/ModerationDialog.vue'
import LoginPage from '../src/pages/LoginPage.vue'
import SettingsPage from '../src/pages/SettingsPage.vue'
import SearchPage from '../src/pages/SearchPage.vue'
import AdminShell from '../src/components/AdminShell.vue'

vi.mock('../src/services/api',()=>({get:vi.fn(),post:vi.fn(),request:vi.fn(),csrfCookie:vi.fn()}))
const admin={id:'1',role:'admin',name:'Admin Démo'}
const dashboard={as_of:'2026-10-10T12:00:00Z',period:7,scope:'demo',kpis:{clients:3,merchants:2,shops:2,vehicles_active:5,vehicles_sold:1,rentals_active:1,reservations_pending:0,transactions_demo:2},fleet:{total:6,available:3,rented:1,sold:1,other:1},series:Object.fromEntries(['registrations','listings','reservations','sales'].map(k=>[k,[{date:'2026-10-09',count:1},{date:'2026-10-10',count:2}]])),geography:[{country:'Côte d’Ivoire',country_code:'CI',city:'Abidjan',count:6}],payments_demo:[{amount_minor:'18500000',currency:'XOF',minor_unit:0,count:1}],activity:[],demo_notice:'Données de démonstration'}
let wrappers=[]
beforeEach(()=>{wrappers.forEach(w=>w.unmount());wrappers=[];vi.resetAllMocks();Object.assign(auth,{user:admin,ready:true,error:null});get.mockImplementation(path=>Promise.resolve({data:path.startsWith('/admin/')?[]:[],meta:{current_page:1,last_page:1,total:0}}));post.mockResolvedValue({data:admin});request.mockResolvedValue({data:admin});csrfCookie.mockResolvedValue(null)})
async function render(component,props={},path='/users',query={}){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/:pathMatch(.*)*',component:{template:'<div/>'}}]});await router.push({path,query});await router.isReady();const wrapper=mount(component,{props,attachTo:document.body,global:{plugins:[router]}});wrappers.push(wrapper);await flushPromises();return {wrapper,router}}
describe('Admin authentication and authorization',()=>{
 it('redirects guests to login preserving private path',async()=>{auth.user=null;auth.ready=false;request.mockRejectedValue({status:401});expect(await adminGuard({path:'/users',fullPath:'/users?page=2'})).toEqual({path:'/login',query:{redirect:'/users?page=2'}})})
 it.each(['customer','merchant'])('refuses role %s',async role=>{auth.user={role};expect(await adminGuard({path:'/dashboard'})).toBe('/forbidden')})
 it('accepts an admin and restores login destination',async()=>{expect(await adminGuard({path:'/vehicles'})).toBeUndefined();expect(await adminGuard({path:'/login',query:{redirect:'/users?page=2'}})).toBe('/users?page=2')})
 it.each(['https://evil.invalid','//evil.invalid','/vehicles\\evil','/not-admin'])('rejects unsafe redirect %s',value=>{expect(safeDestination(value)).toBe('/dashboard')})
 it('uses CSRF and never persists a bearer token',async()=>{await login({email:'admin@bolidemarket.demo',password:'local'});expect(csrfCookie).toHaveBeenCalledOnce();expect(post).toHaveBeenCalledWith('/auth/login',{email:'admin@bolidemarket.demo',password:'local'},{quiet401:true});expect(auth.user.role).toBe('admin');expect(localStorage.length).toBe(0)})
 it('logs out on the server',async()=>{await logout();expect(post).toHaveBeenCalledWith('/auth/logout');expect(auth.user).toBeNull()})
 it('keeps session when logout network fails',async()=>{post.mockRejectedValue(new Error('Réseau indisponible'));await expect(logout()).rejects.toThrow();expect(auth.user).toEqual(admin)})
 it('login has no public registration',async()=>{const {wrapper}=await render(LoginPage,{},'/login');expect(wrapper.text()).toContain('Aucune inscription publique ADMIN');expect(wrapper.find('input[autocomplete="current-password"]').exists()).toBe(true)})
})
describe('Admin supervision screens',()=>{
 it('renders server KPI, exact fleet and multi-currency-safe DEMO amounts',async()=>{get.mockResolvedValue({data:dashboard});const {wrapper}=await render(DashboardPage,{},'/dashboard');expect(wrapper.text()).toContain('6 véhicules');expect(wrapper.text()).toContain('18 500 000 FCFA (XOF)');expect(wrapper.findAll('.kpis article')).toHaveLength(8);expect(wrapper.findAll('polyline')).toHaveLength(4)})
 it('changes report period in URL then reloads API',async()=>{get.mockResolvedValue({data:dashboard});const {wrapper,router}=await render(DashboardPage,{},'/reports');await wrapper.find('select').setValue('90');await flushPromises();expect(router.currentRoute.value.query.period).toBe('90');expect(get).toHaveBeenLastCalledWith('/admin/reports',{period:'90'},expect.any(AbortSignal))})
 it.each(['users','merchants','shops','vehicles','reservations','orders','payments','receipts'])('renders %s from paginated backend response',async type=>{get.mockImplementation(path=>Promise.resolve({data:path==='/admin/'+type?[{id:'2',name:'QA Démo',title:'Toyota',reference:'BM-QA',status:'pending',is_demo:true,amount_minor:'45000',total_minor:'45000',currency:'XOF',minor_unit:0}]:[],meta:{current_page:1,last_page:2,total:21}}));const {wrapper}=await render(EntityList,{type},'/'+type);expect(wrapper.findAll('tbody tr')).toHaveLength(1);expect(wrapper.text()).toContain('21 résultats');expect(wrapper.find('a[href="/'+type+'/'+(type==='receipts'?'BM-QA':'2')+'"]').exists()).toBe(true)})
 it('synchronizes filters and pagination in query string',async()=>{const {wrapper,router}=await render(EntityList,{type:'users'});await wrapper.find('.filters input').setValue('djak');await wrapper.find('.filters').trigger('submit');await flushPromises();expect(router.currentRoute.value.query).toEqual({q:'djak',page:'1'});expect(get).toHaveBeenLastCalledWith('/admin/users',{q:'djak',page:'1'},expect.any(AbortSignal))})
 it('allows merchant approval with mandatory audited reason',async()=>{const {wrapper}=await render(ModerationDialog,{target:{type:'merchants',id:'4',action:'approve',label:'Pro QA'}});expect(wrapper.find('button[type="submit"]').exists()).toBe(false);await wrapper.find('textarea').setValue('Dossier vérifié en démonstration');await wrapper.find('form').trigger('submit');await flushPromises();expect(post).toHaveBeenCalledWith('/admin/merchants/4/actions',{action:'approve',reason:'Dossier vérifié en démonstration'});expect(wrapper.emitted('done')).toHaveLength(1)})
 it('retains moderation reason when backend rejects action',async()=>{post.mockRejectedValue(Object.assign(new Error('Conflit'),{fields:{action:['Vous ne pouvez pas suspendre votre propre compte.']}}));const {wrapper}=await render(ModerationDialog,{target:{type:'users',id:'1',action:'suspend',label:'Admin'}});await wrapper.find('textarea').setValue('Vérification test');await wrapper.find('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('propre compte');expect(wrapper.find('textarea').element.value).toBe('Vérification test');expect(wrapper.emitted('done')).toBeUndefined()})
 it('shows professional empty state',async()=>{const {wrapper}=await render(EntityList,{type:'shops'},'/shops');expect(wrapper.text()).toContain('Aucun résultat dans ce périmètre')})
 it('renders 403 errors and retry',async()=>{get.mockRejectedValue(Object.assign(new Error('Accès réservé'),{status:403}));const {wrapper}=await render(EntityList,{type:'vehicles'},'/vehicles');expect(wrapper.text()).toContain('Accès refusé');expect(wrapper.text()).toContain('Réessayer')})
 it('renders vehicle moderation and related history without amount editing',async()=>{get.mockResolvedValue({data:{id:'9',title:'Toyota RAV4',images:[],reference:'BM-QA',sale_price:{amount_minor:'18500000',currency:'XOF',minor_unit:0},related:{orders:{count:0,filters:{vehicle_id:9},items:[]}},activity:[]}});const {wrapper}=await render(EntityDetail,{type:'vehicles',id:'9'},'/vehicles/9');expect(wrapper.text()).toContain('Dépublier');expect(wrapper.text()).toContain('Marquer pour vérification');expect(wrapper.text()).toContain('Aucune opération');expect(wrapper.find('input').exists()).toBe(false)})
 it('receipt detail is immutable and offers PDF and print',async()=>{get.mockResolvedValue({data:{reference:'BM-RCP-QA',type:'sale',is_demo:true,issued_at:'2026-10-10T12:00:00Z',currency:'XOF',minor_unit:0,total_minor:'18500000',subtotal_minor:'18500000',fees_minor:'0',payment_status:'paid',payment_method:'CARD_DEMO',buyer:{name:'Djak'},seller:{name:'Pro QA'},vehicle:{brand:'Toyota',model:'RAV4'},transaction:{order_reference:'BM-ORD-QA',payment_reference:'BM-PAY-QA'}}});const {wrapper}=await render(EntityDetail,{type:'receipts',id:'BM-RCP-QA'},'/receipts/BM-RCP-QA');expect(wrapper.text()).toContain('Lecture uniquement');expect(wrapper.text()).toContain('Télécharger le PDF');expect(wrapper.find('a[href*="/admin/receipts/BM-RCP-QA/pdf"]').exists()).toBe(true);expect(wrapper.find('textarea').exists()).toBe(false)})
 it('search links references to real resources',async()=>{get.mockResolvedValue({data:[{type:'receipts',reference:'BM-RCP-QA',id:'9',label:'BM-RCP-QA'}]});const {wrapper}=await render(SearchPage,{},'/search',{q:'BM-RCP'});expect(wrapper.find('a[href="/receipts/BM-RCP-QA"]').exists()).toBe(true)})
 it('settings are read only',async()=>{get.mockResolvedValue({data:{payments:'DEMO uniquement',countries:[],retention:'Historique conservé'}});const {wrapper}=await render(SettingsPage,{},'/settings');expect(wrapper.text()).toContain('Lecture uniquement');expect(wrapper.text()).toContain('DEMO uniquement');expect(wrapper.find('input').exists()).toBe(false)})
 it('mobile navigation remains accessible',async()=>{const {wrapper}=await render(AdminShell);expect(wrapper.find('aside').classes()).not.toContain('open');await wrapper.find('.menu-toggle').trigger('click');expect(wrapper.find('aside').classes()).toContain('open');expect(wrapper.find('.scrim').exists()).toBe(true)})
 it('formats large integer minor units without floating-point loss',()=>{expect(money('99999999999999','EUR',2)).toBe('999 999 999 999,99 EUR');expect(cell({rental_daily_price:{amount_minor:'45000',currency:'XOF',minor_unit:0,unit:'day'}},'price')).toContain('/ jour')})
})
