<script setup>
import { receiptMoney,receiptDate } from './receiptFormat'
defineProps({receipt:Object})
const location=p=>[p.district,p.city,p.country].filter(Boolean).join(' · ')
const methods={MOBILE_MONEY_DEMO:'Mobile Money DEMO',CARD_DEMO:'Carte DEMO',CASH_DEMO:'Espèces DEMO',BANK_TRANSFER_DEMO:'Virement DEMO'}
</script>
<template><article class="receipt-document" aria-label="Reçu BolideMarket"><header class="receipt-head"><img src="/images/logo-horizontal.webp" alt="BolideMarket — Achetez. Louez. Roulez."/><div><p>REÇU {{ receipt.type==='sale'?'DE VENTE':'DE LOCATION' }}</p><strong>{{ receipt.reference }}</strong><p>{{ receiptDate(receipt.issued_at) }} UTC</p></div></header><div class="receipt-demo"><strong>REÇU DE DÉMONSTRATION</strong><p>{{ receipt.demo_notice }}</p></div><div class="receipt-parties"><section><p class="receipt-label">CLIENT</p><h2>{{ receipt.buyer.name }}</h2><p>{{ receipt.buyer.email }}</p><p>{{ receipt.buyer.phone }}</p><p>{{ location(receipt.buyer) }}</p></section><section><p class="receipt-label">PROFESSIONNEL</p><h2>{{ receipt.seller.name }}</h2><p>{{ receipt.seller.address }}</p><p>{{ location(receipt.seller) }}</p><p>{{ receipt.seller.phone }}</p><p>{{ receipt.seller.email }}</p></section></div><section class="receipt-vehicle"><p class="receipt-label">VÉHICULE · {{ receipt.type==='sale'?'ACHAT':'LOCATION' }}</p><h2>{{ receipt.vehicle.brand }} {{ receipt.vehicle.model }} {{ receipt.vehicle.trim }}</h2><p>{{ receipt.vehicle.year }} · {{ receipt.vehicle.category }}</p><p>Référence : {{ receipt.vehicle.reference }}</p></section><section v-if="receipt.type==='rental'" class="receipt-rental"><h2>Votre location</h2><p>Du {{ receiptDate(receipt.transaction.starts_at,receipt.transaction.timezone) }} au {{ receiptDate(receipt.transaction.ends_at,receipt.transaction.timezone) }}</p><p>{{ receipt.transaction.days }} jour(s) · {{ receiptMoney({...receipt,total_minor:receipt.transaction.daily_price_minor}) }} / jour</p><small>Fuseau : {{ receipt.transaction.timezone }}</small></section><dl class="receipt-totals"><div><dt>{{ receipt.type==='sale'?'Prix du véhicule':'Sous-total location' }}</dt><dd>{{ receiptMoney(receipt,'subtotal_minor') }}</dd></div><div><dt>Frais</dt><dd>{{ receiptMoney(receipt,'fees_minor') }}</dd></div><div class="receipt-total"><dt>TOTAL</dt><dd>{{ receiptMoney(receipt) }} <small>{{ receipt.currency }}</small></dd></div></dl><section class="receipt-payment"><h2>Paiement simulé réussi</h2><p>{{ methods[receipt.payment_method] || receipt.payment_method }}</p><p>Opération : {{ receipt.transaction.reservation_reference || receipt.transaction.order_reference }}</p><p>Ce reçu n’est pas une facture fiscale. Il atteste uniquement de la simulation enregistrée à son émission.</p></section><footer>BolideMarket · Achetez. Louez. Roulez.<br>{{ receipt.reference }} · © {{ new Date(receipt.issued_at).getUTCFullYear() }} BolideMarket</footer></article></template>
<style scoped>
.receipt-document{background:white;color:#0B0D0F;border:1px solid #ddd;border-radius:8px;max-width:900px;margin:24px 0;overflow:hidden;font-size:14px;overflow-wrap:anywhere}
.receipt-head{display:flex;gap:24px;align-items:center;justify-content:space-between;padding:28px;background:#0B0D0F;color:#F5F3EE;font-size:11px}.receipt-head img{width:240px;max-width:45%;height:auto;object-fit:contain}.receipt-head strong{display:block}.receipt-head>div{text-align:right}
.receipt-demo{margin:28px;padding:14px 18px;border-left:4px solid #E85D2A;background:#F5F3EE}.receipt-demo strong{font-size:12px}.receipt-demo p{margin-top:6px}
.receipt-parties{display:grid;grid-template-columns:1fr 1fr;gap:32px;padding:0 28px 24px}.receipt-document h2{font-size:18px;margin:8px 0 10px}.receipt-document p{margin:5px 0}.receipt-label{font-size:10px;font-weight:700;letter-spacing:.1em}
.receipt-vehicle{margin:0 28px;padding:18px 0;border-block:1px solid #ddd}.receipt-rental{padding:18px 28px 0}.receipt-totals{margin:24px 28px}.receipt-totals>div{display:flex;justify-content:space-between;gap:20px;padding:14px;border-bottom:1px solid #ddd}.receipt-totals dd{margin:0;text-align:right;font-weight:650}.receipt-total{background:#0B0D0F;color:#F5F3EE;font-size:20px;border-bottom:4px solid #E85D2A!important}.receipt-total small{font-size:10px;color:inherit}.receipt-payment{padding:0 28px 24px}.receipt-document footer{padding:16px 28px;border-top:1px solid #ddd;font-size:10px;color:#555;background:#F5F3EE}
@media(max-width:600px){.receipt-head{padding:20px;flex-direction:column;align-items:flex-start}.receipt-head img{max-width:100%}.receipt-head>div{text-align:left}.receipt-parties{grid-template-columns:1fr;padding-inline:20px;gap:22px}.receipt-demo{margin:20px}.receipt-total{font-size:16px}.receipt-totals{margin:20px}.receipt-vehicle{margin-inline:20px}}
</style>
