<script setup>
import { ref,watch,onBeforeUnmount } from 'vue'
import ReceiptDocument from './ReceiptDocument.vue'
import ReceiptActions from './ReceiptActions.vue'
import { receiptMoney,receiptDate } from './receiptFormat'
const props=defineProps({get:Function,apiBase:String,scope:String,detailBase:String,reference:String,shopId:[String,Number]})
const data=ref(null),busy=ref(false),error=ref(null),page=ref(1)
let controller,version=0
async function reload(p=page.value){const v=++version;controller?.abort();controller=new AbortController();page.value=p;busy.value=true;error.value=null;try{const result=await props.get('/'+props.scope+'/receipts'+(props.reference?'/'+encodeURIComponent(props.reference):''),props.reference?{}:{page:p,per_page:10,...(props.shopId?{shop_id:props.shopId}:{})},controller.signal);if(v===version)data.value=result}catch(e){if(v===version&&!controller.signal.aborted)error.value=e}finally{if(v===version)busy.value=false}}
watch(()=>[props.reference,props.shopId],()=>reload(1),{immediate:true})
onBeforeUnmount(()=>{version++;controller?.abort()})
defineExpose({reload})
</script>
<template><div class="receipts-browser"><RouterLink v-if="reference" :to="detailBase" class="text-button">← Tous les reçus</RouterLink><h1>{{ reference?'Votre reçu':'Reçus' }}</h1><p class="receipt-lead">Documents de démonstration. Aucun paiement réel. Aucune facture fiscale.</p><p v-if="busy" role="status">Chargement des reçus…</p><section v-else-if="error" role="alert" class="receipt-empty"><h2>Reçu indisponible</h2><p>{{ error.message }}</p><button class="button secondary" @click="reload()">Réessayer</button></section><template v-else-if="data"><template v-if="reference"><ReceiptActions :reference="data.data.reference" :api-base="apiBase" :scope="scope"/><p class="help">« Imprimer » ouvre le PDF. Utilisez ensuite la commande d’impression de votre navigateur.</p><ReceiptDocument :receipt="data.data"/></template><template v-else><section v-if="!data.data.length" class="receipt-empty"><h2>Aucun reçu pour le moment.</h2><p>Un reçu apparaîtra après confirmation du paiement simulé par le professionnel.</p></section><article v-for="r in data.data" :key="r.reference" class="receipt-card"><span class="receipt-kind">{{ r.type==='sale'?'Vente':'Location' }} · DÉMONSTRATION</span><h2>{{ r.vehicle.brand }} {{ r.vehicle.model }}</h2><p>{{ r.reference }}</p><p>{{ r.seller.name }}<span v-if="scope==='merchant'"> · {{ r.buyer.name }}</span></p><p>{{ receiptDate(r.issued_at) }} UTC</p><strong class="receipt-amount">{{ receiptMoney(r) }} <small>{{ r.currency }}</small></strong><ReceiptActions :reference="r.reference" :api-base="apiBase" :scope="scope" :detail-base="detailBase"/></article><nav v-if="data.meta?.last_page>1" class="receipt-pages" aria-label="Pagination des reçus"><button class="button secondary" :disabled="page<=1" @click="reload(page-1)">Précédent</button><span>{{ page }} / {{ data.meta.last_page }}</span><button class="button secondary" :disabled="page>=data.meta.last_page" @click="reload(page+1)">Suivant</button></nav></template></template></div></template>
<style scoped>.receipt-lead{margin:12px 0 24px;color:#61656a}.receipt-card,.receipt-empty{background:white;border:1px solid #ddd;border-radius:8px;padding:24px;margin:20px 0;overflow-wrap:anywhere}.receipt-card h2{font-size:22px;margin:10px 0}.receipt-card p{font-size:12px;margin:6px 0}.receipt-kind{font-size:10px;font-weight:650;letter-spacing:.06em}.receipt-amount{display:block;font-size:23px;margin-top:14px}.receipt-amount small{font-size:11px}.receipt-pages{display:flex;gap:16px;align-items:center;justify-content:center}</style>
