<script setup>
import { ref,watch,onBeforeUnmount,computed } from 'vue'
import { get } from '../services/api'
import { config } from '../config'
import { entities,actionLabels,routeFor,cell } from '../entities'
import { auth } from '../stores/auth'
import LoadState from '../components/LoadState.vue'
import DataFields from '../components/DataFields.vue'
import ModerationDialog from '../components/ModerationDialog.vue'
import ReceiptDocument from '../../../web-shared/ReceiptDocument.vue'
import ReceiptActions from '../../../web-shared/ReceiptActions.vue'
const props=defineProps({type:String,id:String}),data=ref(null),busy=ref(false),error=ref(null),target=ref(null)
let controller,version=0
const definition=computed(()=>entities[props.type])
const actions=computed(()=>definition.value.actions.filter(a=>!(props.type==='users'&&props.id===auth.user?.id&&a==='suspend')))
async function load(){const v=++version;controller?.abort();controller=new AbortController();busy.value=true;error.value=null;data.value=null;try{const r=await get('/admin/'+props.type+'/'+encodeURIComponent(props.id),{},controller.signal);if(v===version)data.value=r.data}catch(e){if(v===version&&!controller.signal.aborted)error.value=e}finally{if(v===version)busy.value=false}}
watch(()=>[props.type,props.id],load,{immediate:true})
onBeforeUnmount(()=>{version++;controller?.abort()})
</script>
<template><div><RouterLink class="back" :to="'/'+type">← {{ definition.title }}</RouterLink><div class="page-title"><div><span class="eyebrow">{{ definition.singular }}</span><img v-if="data?.logo_url||data?.avatar_url" class="detail-identity" :src="data.logo_url||data.avatar_url" alt="Photo de profil"><h1>{{ data?.name || data?.title || data?.reference || 'Détail' }}</h1></div><span v-if="data?.is_demo" class="badge">DÉMONSTRATION</span></div><LoadState :busy="busy" :error="error" @retry="load"><template v-if="data"><div class="actions"><button v-for="action in actions" :key="action" class="secondary" @click="target={type,id,action,label:data.name||data.title||data.reference}">{{ actionLabels[action] }}</button><a v-if="type==='shops' || type==='vehicles'" class="button secondary" :href="config.marketplaceUrl+'/'+type+'/'+data.slug" target="_blank" rel="noopener">{{ type==='shops'?'Voir boutique publique':'Voir annonce publique' }} ↗</a><RouterLink v-if="data.receipt_reference" class="button secondary" :to="'/receipts/'+data.receipt_reference">Voir le reçu</RouterLink></div><template v-if="type==='receipts'"><p class="lead">Lecture uniquement · Snapshots historiques · Aucun paiement réel</p><ReceiptActions :reference="data.reference" :api-base="config.apiBase" scope="admin"/><ReceiptDocument :receipt="data"/></template><template v-else><img v-if="data.cover_url" class="cover" :src="data.cover_url" alt="Couverture de la boutique"><div v-if="data.images?.length" class="photos"><img v-for="image in data.images" :key="image.id" :src="image.url" :alt="image.alt_text||data.title"></div><section class="panel"><h2>Informations</h2><DataFields :data="data"/></section><section v-for="(related,key) in data.related" :key="key" class="panel"><div class="section-title"><h2>{{ entities[key].title }} <small>{{ related.count }}</small></h2><RouterLink :to="{path:'/'+key,query:related.filters}">Tous les résultats →</RouterLink></div><p v-if="!related.items.length" class="muted">Aucune opération dans ce périmètre.</p><ul v-else class="related"><li v-for="item in related.items" :key="item.id"><RouterLink :to="routeFor(key,item)">{{ item.reference||item.title||item.name }}</RouterLink><span>{{ cell(item,'status') }}</span><span v-if="item.total_minor">{{ cell(item,'total') }}</span></li></ul></section><section v-if="data.activity" class="panel"><h2>Activité récente</h2><p v-if="!data.activity.length" class="muted">Aucune décision administrative enregistrée pour cette ressource.</p><ul v-else class="related"><li v-for="entry in data.activity" :key="entry.id"><strong>{{ cell(entry,'action') }}</strong><span>{{ entry.reason }}</span><span>{{ cell(entry,'created_at') }}</span></li></ul></section></template></template></LoadState><ModerationDialog v-if="actions.length" :target="target" @close="target=null" @done="load"/></div></template>
