<script setup>
import { computed } from 'vue'
import { formatMoney } from '../utils/format'
import { recordMoney, reservationStatuses, orderStatuses, displayDate, paymentMethods } from '../utils/commerce'
import { vehicleMedia } from '../utils/demoMedia'
import SafeImage from './SafeImage.vue'
const props = defineProps({ record: Object, kind: String, detailed: Boolean })
const rental = computed(() => props.kind === 'reservations')
const media = computed(() => vehicleMedia({ is_demo: props.record.is_demo, model: { name: props.record.vehicle.model } }))
</script>
<template><article class="commerce-record"><div class="record-image"><SafeImage :src="media.src" :alt="record.vehicle.brand + ' ' + record.vehicle.model" /><small v-if="media.illustration">Illustration démo</small></div><div class="record-body"><div class="record-heading"><span class="eyebrow">{{ record.reference }}</span><span class="pill">{{ (rental ? reservationStatuses : orderStatuses)[record.status] || record.status }}</span></div><h2>{{ record.vehicle.brand }} {{ record.vehicle.model }}</h2><p class="muted">{{ record.vehicle.year }} · {{ record.shop.name }}</p><p v-if="rental">{{ displayDate(record.starts_at, record.shop_timezone) }} → {{ displayDate(record.ends_at, record.shop_timezone) }} · {{ record.billable_days }} jour(s)</p><p v-else-if="record.kind === 'rental'" class="help">Commande liée à une location</p><p class="record-price">{{ formatMoney(recordMoney(record)) }}</p><p class="help">Créé le {{ displayDate(record.created_at) }} · {{ paymentMethods[record.payment_method_demo] }}</p><dl v-if="detailed" class="record-details"><div v-if="rental"><dt>Tarif journalier</dt><dd>{{ formatMoney(recordMoney(record, 'daily_price_minor')) }}</dd></div><div><dt>Sous-total</dt><dd>{{ formatMoney(recordMoney(record, 'subtotal_minor')) }}</dd></div><div><dt>Frais</dt><dd>{{ formatMoney(recordMoney(record, 'fees_minor')) }}</dd></div><div><dt>Professionnel</dt><dd>{{ record.shop.name }} · {{ record.shop.address }}</dd></div><div v-if="record.expires_at && record.status === 'pending'"><dt>Retenue temporaire jusqu’à</dt><dd>{{ new Date(record.expires_at).toLocaleString('fr-FR') }}</dd></div><div><dt>Paiement de démonstration</dt><dd>{{ (record.payment || record.order?.payment)?.status === 'paid' ? 'Simulé avec succès' : 'En attente de confirmation professionnelle' }}</dd></div></dl><RouterLink v-if="!detailed" class="text-button" :to="'/account/' + kind + '/' + record.id">Voir le détail →</RouterLink><p v-if="record.status === 'pending'" class="help">Demande enregistrée. Confirmation du professionnel requise avant l’expiration de la retenue.</p></div></article></template>

