<script setup>
import { ref } from 'vue'
const props=defineProps({modelValue:Object,timezone:String})
const emit=defineEmits(['update:modelValue'])
const locating=ref(false),locationError=ref('')
function set(key,value){emit('update:modelValue',{...props.modelValue,[key]:value})}
function mode(event){emit('update:modelValue',{...props.modelValue,mode:event.target.value,address:'',city:'',latitude:null,longitude:null,contact_name:event.target.value==='proxy'?'':props.modelValue.contact_name})}
function locate(){locationError.value='';if(!navigator.geolocation){locationError.value='La géolocalisation n’est pas disponible. Renseignez votre adresse.';return}locating.value=true;navigator.geolocation.getCurrentPosition(p=>{emit('update:modelValue',{...props.modelValue,latitude:p.coords.latitude,longitude:p.coords.longitude});locating.value=false},()=>{locationError.value='Position non obtenue. Vous pouvez saisir votre adresse et vos coordonnées manuellement.';locating.value=false},{timeout:10000,maximumAge:60000})}
</script>
<template><fieldset class="handover-form"><legend>Comment souhaitez-vous recevoir le véhicule ?</legend><label>Mode de remise<select :value="modelValue.mode" @change="mode"><option value="self">Je viens chercher le véhicule</option><option value="proxy">J’envoie une personne à ma place</option><option value="delivery">Je souhaite une livraison par chauffeur</option></select></label><label>Date et heure approximative<input :value="modelValue.scheduled_local" type="datetime-local" required @input="set('scheduled_local',$event.target.value)"/></label><p class="help">Heure de la boutique : {{ timezone }}. Le rendez-vous et, le cas échéant, la livraison restent à confirmer avec le professionnel.</p><div class="form-pair"><label>{{ modelValue.mode==='proxy'?'Nom de la personne mandatée':'Nom du contact' }}<input :value="modelValue.contact_name" required maxlength="120" @input="set('contact_name',$event.target.value)"/></label><label>{{ modelValue.mode==='proxy'?'Téléphone de la personne mandatée':'Téléphone du contact' }}<input :value="modelValue.contact_phone" type="tel" required placeholder="+225…" maxlength="40" @input="set('contact_phone',$event.target.value)"/></label></div><template v-if="modelValue.mode==='delivery'"><label>Ville de livraison<input :value="modelValue.city" required maxlength="120" @input="set('city',$event.target.value)"/></label><label>Adresse et point de repère<textarea :value="modelValue.address" required maxlength="500" @input="set('address',$event.target.value)"/></label><button class="button secondary" type="button" :disabled="locating" @click="locate">{{ locating?'Recherche de position…':'Utiliser ma position (facultatif)' }}</button><p v-if="locationError" class="help" role="status">{{ locationError }}</p><div class="form-pair"><label>Latitude (facultatif)<input :value="modelValue.latitude" type="number" step="any" min="-90" max="90" @input="set('latitude',$event.target.value===''?null:Number($event.target.value))"/></label><label>Longitude (facultatif)<input :value="modelValue.longitude" type="number" step="any" min="-180" max="180" @input="set('longitude',$event.target.value===''?null:Number($event.target.value))"/></label></div><p class="help">Aucun chauffeur n’est automatiquement affecté. Les modalités et frais éventuels sont à convenir avec le professionnel.</p></template><label>Précisions (facultatif)<textarea :value="modelValue.notes" maxlength="1000" @input="set('notes',$event.target.value)"/></label></fieldset></template>
