<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><title>{{ $r->reference }}</title><style>
@page{margin:38px 40px 56px}body{font-family:"DejaVu Sans",sans-serif;font-size:10px;line-height:1.5;color:#0B0D0F}
table{width:100%;border-collapse:collapse;table-layout:fixed}td{vertical-align:top;overflow-wrap:break-word}h1,h2,p{margin:0}h1{font-size:22px;line-height:1.2}h2{font-size:14px;margin:5px 0 10px}.muted{color:#61656a}.header{background:#0B0D0F;color:#F5F3EE;padding:20px;margin-bottom:20px}.logo{width:220px;height:auto}.brand{font-size:19px;font-weight:bold}.tagline{font-size:9px}.right{text-align:right}.eyebrow{font-size:9px;font-weight:bold;letter-spacing:1px;color:#555;margin-bottom:8px}.demo{background:#F5F3EE;border-left:4px solid #E85D2A;padding:12px 15px;margin-bottom:22px}.demo strong{font-size:10px}.parties td{width:50%;padding:0 14px 20px 0}.parties p{margin-bottom:3px}.vehicle{border-top:1px solid #ddd;border-bottom:1px solid #ddd;padding:15px 0;margin-bottom:18px}.summary th{text-align:left;font-size:9px;padding:8px 10px;background:#F5F3EE}.summary td{padding:11px 10px;border-bottom:1px solid #e2e2e2}.summary .right{text-align:right}.total td{background:#0B0D0F;color:#F5F3EE;font-size:17px;font-weight:bold;border-bottom:4px solid #E85D2A}.payment{margin-top:20px}.foot{position:fixed;bottom:-32px;left:0;right:0;font-size:8px;color:#61656a;border-top:1px solid #ddd;padding-top:8px}.small{font-size:8px}.block{page-break-inside:avoid}
</style></head><body>
<div class="foot">BolideMarket · Achetez. Louez. Roulez.<br>{{ $r->reference }} · © {{ $r->issued_at->year }} BolideMarket</div>
<div class="header"><table><tr><td style="width:245px">@if($logo)<img class="logo" src="{{ $logo }}" alt="BolideMarket - Achetez. Louez. Roulez.">@else<div class="brand">BolideMarket</div><div class="tagline">Achetez. Louez. Roulez.</div>@endif</td><td class="right" style="width:200px"><h1>REÇU</h1><div class="small">{{ $r->reference }}</div><div>{{ $r->issued_at->format('d/m/Y H:i') }} UTC</div></td></tr></table></div>
<div class="demo"><strong>REÇU DE DÉMONSTRATION</strong><p>Document généré dans le cadre d’une démonstration BolideMarket.<br>Aucun paiement réel n’a été effectué.</p></div>
<table class="parties"><tr><td><p class="eyebrow">CLIENT</p><h2>{{ $buyer['name'] ?? 'Non renseigné' }}</h2><p>{{ $buyer['email'] ?? '' }}</p><p>{{ $buyer['phone'] ?? '' }}</p><p>{{ implode(' · ',array_filter([$buyer['city']??null,$buyer['country']??null])) }}</p></td><td><p class="eyebrow">PROFESSIONNEL</p><h2>{{ $seller['name'] ?? 'Non renseigné' }}</h2><p>{{ $seller['address'] ?? '' }}</p><p>{{ implode(' · ',array_filter([$seller['district']??null,$seller['city']??null,$seller['country']??null])) }}</p><p>{{ $seller['phone'] ?? '' }}</p><p>{{ $seller['email'] ?? '' }}</p></td></tr></table>
<div class="vehicle block"><p class="eyebrow">VÉHICULE · {{ $r->type->value === 'sale' ? 'ACHAT' : 'LOCATION' }}</p><h2>{{ $vehicle['brand'] ?? '' }} {{ $vehicle['model'] ?? '' }} {{ $vehicle['trim'] ?? '' }}</h2><p>{{ $vehicle['year'] ?? '' }} @if(!empty($vehicle['category'])) · {{ $vehicle['category'] }} @endif</p><p class="muted">Référence véhicule : {{ $vehicle['reference'] ?? 'Non renseignée' }}</p></div>
@if($r->type->value === 'rental')<div class="block" style="margin-bottom:15px"><h2>Votre location</h2><p>Du {{ \Carbon\CarbonImmutable::parse($tx['starts_at'])->setTimezone($tx['timezone'])->format('d/m/Y H:i') }} au {{ \Carbon\CarbonImmutable::parse($tx['ends_at'])->setTimezone($tx['timezone'])->format('d/m/Y H:i') }}</p><p>{{ $tx['days'] }} jour(s) · {{ $money($tx['daily_price_minor']) }} / jour</p><p class="small muted">Fuseau : {{ $tx['timezone'] }}</p></div>@endif
<table class="summary block"><tr><th>DÉSIGNATION</th><th class="right">MONTANT ({{ $r->currency_code }})</th></tr><tr><td>{{ $r->type->value === 'sale' ? 'Prix du véhicule' : 'Sous-total de location' }}</td><td class="right">{{ $money($r->subtotal_minor) }}</td></tr><tr><td>Frais</td><td class="right">{{ $money($r->fees_minor) }}</td></tr><tr class="total"><td>TOTAL</td><td class="right">{{ $money($r->total_minor) }}</td></tr></table>
<div class="payment block"><h2>Paiement simulé réussi</h2><p>Méthode : {{ ['MOBILE_MONEY_DEMO'=>'Mobile Money DEMO','CARD_DEMO'=>'Carte DEMO','CASH_DEMO'=>'Espèces DEMO','BANK_TRANSFER_DEMO'=>'Virement DEMO'][$r->payment_method] ?? $r->payment_method }}</p><p>Opération : {{ $tx['reservation_reference'] ?? $tx['order_reference'] }}</p><p class="small muted">Paiement : {{ $tx['payment_reference'] }}<br>Ce reçu n’est pas une facture fiscale. Il atteste uniquement de la simulation enregistrée à son émission.</p></div>
</body></html>
