<script setup>
import { useMerchantRealtime } from '../composables/useMerchantRealtime'
import { ref,computed,onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { currentShop } from '../stores/shop'
import { merchantReservationService,merchantOrderService } from '../services/merchant'
import { labels,date,moneyOf } from '../utils/pro'
import { formatMoney } from '../utils/format'
import AsyncState from '../components/AsyncState.vue'
import Pagination from '../components/Pagination.vue'
const route=useRoute(),sale=computed(()=>route.path==='/orders'),rentals=computed(()=>route.path==='/rentals')
const rows=ref([]),meta=ref(null),busy=ref(false),error=ref(null),status=ref(''),q=ref('')
const states=computed(()=>sale.value?['pending','confirmed','fulfilled','cancelled']:rentals.value?['active','completed']:['pending','confirmed','active','completed','cancelled','rejected','expired'])
let version=0
async function load(page=1){const n=++version;busy.value=true;error.value=null;try{const r=await(sale.value?merchantOrderService:merchantReservationService).list({shop_id:currentShop.value?.id,page,status:status.value,q:q.value,...(sale.value?{kind:'sale'}:rentals.value?{rentals:1}:{})});if(n===version){rows.value=r.data;meta.value=r.meta}}catch(e){if(n===version)error.value=e}finally{if(n===version)busy.value=false}}
onMounted(()=>load())
useMerchantRealtime(() => load(meta.value?.current_page || 1), e => e.type.startsWith(sale.value?'Order':'Reservation'))
</script><template><div class="page-heading"><div><h1>{{ route.meta.title }}</h1><p class="lead">{{ rentals?'Les locations en cours et terminées.':'Consultez les demandes de vos clients et leur suivi.' }}</p></div><button class="button secondary" :disabled="busy" @click="load()">Actualiser ↻</button></div><form class="filterbar panel" @submit.prevent="load()"><label>Rechercher<input v-model="q" type="search" placeholder="Référence, véhicule ou client"/></label><label>Statut<select v-model="status"><option value="">Tous les statuts</option><option v-for="s in states" :key="s" :value="s">{{ labels[s] }}</option></select></label><button class="button" :disabled="busy">Filtrer</button></form><AsyncState :busy="busy" :error="error" @retry="load()"><section class="panel"><div v-if="!rows.length" class="empty"><h2>Aucune {{ sale?'vente':'réservation' }} à afficher.</h2><p>Les nouvelles demandes apparaîtront ici.</p><RouterLink to="/vehicles">Consulter mon parc →</RouterLink></div><div v-else class="table-wrap"><table><thead><tr><th>Référence / Client</th><th>Véhicule</th><th v-if="!sale">Période</th><th>Total</th><th>Statut</th><th>Date</th><th>Action</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><strong>{{ r.customer?.name || 'Client' }}</strong><small>{{ r.reference }}</small></td><td>{{ r.vehicle?.title }}</td><td v-if="!sale">{{ date(r.starts_at) }} → {{ date(r.ends_at) }}<small>{{ r.billable_days }} jour(s)</small></td><td class="nowrap"><strong>{{ formatMoney(moneyOf(r)) }}</strong><small v-if="r.payment">{{ labels[r.payment.status] || r.payment.status }}</small></td><td><span class="badge" :class="r.status">{{ labels[r.status] }}</span></td><td class="nowrap">{{ date(r.created_at) }}</td><td><RouterLink :to="'/'+(sale?'orders':'reservations')+'/'+r.id">Consulter →</RouterLink></td></tr></tbody></table></div><Pagination :meta="meta" @page="load"/></section></AsyncState></template>