<script setup>
import ReceiptActions from '../../../web-shared/ReceiptActions.vue'
import { config } from '../config'
import { useMerchantRealtime } from '../composables/useMerchantRealtime'
import { ref,computed,onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { merchantReservationService,merchantOrderService } from '../services/merchant'
import { useLoad } from '../composables/useLoad'
import { labels,date,moneyOf } from '../utils/pro'
import { formatMoney } from '../utils/format'
import { notify } from '../stores/toasts'
import AsyncState from '../components/AsyncState.vue'
import OrderHandoverSummary from '../components/OrderHandoverSummary.vue'
import FormError from '../components/FormError.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
const route=useRoute(),sale=route.path.startsWith('/orders/'),api=sale?merchantOrderService:merchantReservationService
const {data:r,busy,error,load}=useLoad(()=>api.get(route.params.id)),action=ref(''),saving=ref(false),actionError=ref(null)
const actionLabels={confirm:'Confirmer',reject:'Refuser',cancel:'Annuler',start:'Remettre le véhicule',complete:'Terminer la location',fulfil:'Livrer le véhicule'}
const actions=computed(()=>{if(!r.value)return [];if(sale){if(r.value.kind!=='sale')return [];return r.value.status==='pending'?['confirm','cancel']:r.value.status==='confirmed'?['fulfil','cancel']:[]}if(r.value.status==='pending')return ['confirm','reject','cancel'];if(r.value.status==='active')return ['complete'];if(r.value.status==='confirmed'){const start=new Date(r.value.starts_at),end=new Date(r.value.ends_at),now=new Date();return start>now?['cancel']:end>now?['start']:[]}return []})
async function perform(){saving.value=true;actionError.value=null;try{await api.action(r.value.id,action.value);action.value='';notify('Opération enregistrée.');await load()}catch(e){actionError.value=e}finally{saving.value=false}}
onMounted(load)
useMerchantRealtime(() => load(true), e => e.type.startsWith(sale?'Order':'Reservation') && String(e.data.id)===String(route.params.id))
</script><template><RouterLink class="back" :to="sale?'/orders':'/reservations'">← Retour à la liste</RouterLink><AsyncState :busy="busy" :error="error" @retry="load"><template v-if="r"><div class="page-heading"><div><p class="eyebrow">{{ r.reference }}</p><h1>{{ r.vehicle?.title }}</h1><p>Demande du {{ date(r.created_at) }}</p></div><span class="badge" :class="r.status">{{ labels[r.status] }}</span></div><div class="detail-grid"><section class="panel"><h2>Client</h2><h3>{{ r.customer?.name || 'Client' }}</h3><p>{{ r.customer?.email }}</p><p>{{ r.customer?.phone || 'Téléphone non renseigné' }}</p><h2>{{ sale?'Vente':'Location' }}</h2><dl class="facts"><template v-if="!sale"><dt>Début</dt><dd>{{ date(r.starts_at) }}</dd><dt>Fin</dt><dd>{{ date(r.ends_at) }}</dd><dt>Durée</dt><dd>{{ r.billable_days }} jour(s)</dd><dt>Fuseau</dt><dd>{{ r.shop_timezone }}</dd></template><dt>Boutique</dt><dd>{{ r.shop?.name }}</dd><dt>Devise</dt><dd>{{ r.currency }}</dd></dl></section><section class="panel"><h2>Montant de l’opération</h2><p class="large-price">{{ formatMoney(moneyOf(r)) }}</p><p>Méthode : {{ r.payment_method_demo }}</p><p>État paiement : {{ (r.payment || r.order?.payment)?.status==='paid'?'Payé (DEMO)':'En attente de confirmation' }}</p><p class="notice">Simulation uniquement. Aucun encaissement réel. La confirmation enregistre un paiement DEMO côté serveur ; une annulation ne simule pas son remboursement.</p><div class="actions"><button v-for="a in actions" :key="a" class="button" :class="{secondary:['cancel','reject'].includes(a)}" @click="actionError=null;action=a">{{ actionLabels[a] }}</button></div><p v-if="!actions.length" class="help">Aucune action disponible dans cet état ou à cette date.</p></section></div><section class="panel"><OrderHandoverSummary :handover="r.handover"/><p v-if="r.price_offer_id" class="notice">Prix négocié : proposition acceptée n° {{ r.price_offer_id }}.</p><ReceiptActions :reference="r.receipt_reference" :api-base="config.apiBase" scope="merchant" detail-base="/receipts"/><h2>Suivi</h2><p>Demande reçue : {{ date(r.created_at) }}</p><p v-if="r.confirmed_at || r.order?.confirmed_at">Confirmation : {{ date(r.confirmed_at || r.order?.confirmed_at) }}</p><p v-if="r.fulfilled_at || r.order?.fulfilled_at">Clôture : {{ date(r.fulfilled_at || r.order?.fulfilled_at) }}</p><p v-if="r.expires_at">Expiration de la demande : {{ new Date(r.expires_at).toLocaleString('fr-FR') }}</p><p>État actuel : {{ labels[r.status] }}</p></section></template></AsyncState><ConfirmDialog :open="!!action" :title="actionLabels[action]+' cette opération ?'" :busy="saving" @close="action=''" @confirm="perform"><p>Le serveur vérifiera la disponibilité du véhicule et les conditions de cette transition.</p><FormError :error="actionError"/></ConfirmDialog></template>