<script setup>
import { ref,onBeforeUnmount } from 'vue'
import { currentShop,updateShop } from '../stores/shop'
import { merchantShopService as api } from '../services/merchant'
import { useReferences } from '../composables/useReferences'
import { notify } from '../stores/toasts'
import { config } from '../config'
import FormError from '../components/FormError.vue'
import ProfileLocation from '../components/ProfileLocation.vue'
import SafeImage from '../components/SafeImage.vue'
const {references}=useReferences(),busy=ref(false),error=ref(null),files=ref({}),previews=ref({})
const s=currentShop.value,fields=ref(s?{name:s.name,description:s.description||'',email:s.email||'',phone:s.phone||'',address:s.address,timezone:s.timezone,country_code:s.location.country.code,city_id:s.location.city.id,district_id:s.location.district?.id||'',opening_hours:s.opening_hours||Array.from({length:7},(_,i)=>({day:i+1,closed:true,opens:null,closes:null}))}:null)
const days=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche']
function photo(kind,event){const f=event.target.files[0];if(!f)return;error.value=null;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>3*1024*1024){error.value=new Error('Choisissez une image JPG, PNG ou WebP de 3 Mo maximum.');return}if(previews.value[kind])URL.revokeObjectURL(previews.value[kind]);files.value[kind]=f;previews.value[kind]=URL.createObjectURL(f)}
async function save(){busy.value=true;error.value=null;try{updateShop((await api.update(s.id,{...fields.value,district_id:fields.value.district_id||null,email:fields.value.email||null,phone:fields.value.phone||null,opening_hours:fields.value.opening_hours.map(h=>({...h,opens:h.closed?null:h.opens,closes:h.closed?null:h.closes}))})).data);for(const kind of ['logo','cover'])if(files.value[kind]){updateShop((await api.media(s.id,kind,files.value[kind])).data);delete files.value[kind];URL.revokeObjectURL(previews.value[kind]);delete previews.value[kind]}notify('Boutique mise à jour.')}catch(e){error.value=e}finally{busy.value=false}}
onBeforeUnmount(()=>Object.values(previews.value).forEach(URL.revokeObjectURL))
</script><template><div class="page-heading"><div><h1>Ma boutique</h1><p class="lead">Votre vitrine et vos coordonnées publiques.</p></div><a v-if="s" class="button secondary" :href="config.marketplaceUrl+'/shops/'+s.slug" target="_blank" rel="noopener">Voir ma boutique publique ↗</a></div><p v-if="!s" class="panel">Aucune boutique associée à ce compte.</p><form v-else @submit.prevent="save"><FormError :error="error"/><fieldset :disabled="busy"><section class="panel"><h2>Identité de la boutique</h2><label>Nom de la boutique<input v-model="fields.name" required maxlength="150"/></label><label>Description<textarea v-model="fields.description" rows="4" maxlength="5000"/></label><div class="form-grid"><label>Téléphone public<input v-model="fields.phone" type="tel" placeholder="+225…"/></label><label>E-mail public<input v-model="fields.email" type="email"/></label></div><label>Adresse<input v-model="fields.address" required maxlength="255"/></label><div class="form-grid"><label>Pays<select v-model="fields.country_code" required @change="fields.city_id='';fields.district_id=''"><option v-for="c in references.countries" :key="c.code" :value="c.code">{{ c.name }}</option></select></label><label>Fuseau horaire<input v-model="fields.timezone" required placeholder="Africa/Abidjan"/></label></div><ProfileLocation v-model="fields" required/><p class="help">Devise : {{ references.countries.find(c=>c.code===fields.country_code)?.currency_code }} — déterminée par le pays. Le changement de pays est bloqué dès que la boutique possède des véhicules ou des transactions.</p></section><section class="panel"><h2>Horaires d’ouverture</h2><p class="help">Horaires locaux de la boutique. Une plage par jour.</p><div v-for="h in fields.opening_hours" :key="h.day" class="hours-row"><strong>{{ days[h.day-1] }}</strong><label class="check"><input v-model="h.closed" type="checkbox"/>Fermé</label><label>Ouverture<input v-model="h.opens" type="time" :disabled="h.closed" :required="!h.closed"/></label><label>Fermeture<input v-model="h.closes" type="time" :disabled="h.closed" :required="!h.closed"/></label></div></section><section class="panel"><h2>Identité visuelle</h2><div class="form-grid"><label v-for="[kind,label] in [['logo','Logo'],['cover','Couverture']]" :key="kind">{{ label }}<SafeImage class="shop-preview" :src="previews[kind] || currentShop[kind+'_url']" :alt="label+' boutique'"/><input type="file" accept="image/jpeg,image/png,image/webp" @change="photo(kind,$event)"/><small>JPG, PNG ou WebP · 3 Mo maximum.</small></label></div></section><button class="button" :disabled="busy">{{ busy?'Enregistrement…':'Enregistrer les modifications' }}</button></fieldset></form></template>